build:
    environment:
        python: '3.4.1'
    dependencies:
        before:
            - 'sudo apt-get install -y mercurial python-dev'
        override:
            - true
    tests:
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - '*tests*'
        - 'fabfile.py'
        - 'docs/*'
        - '*migrations*'
        - '*south_migrations*'
