language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
cache: pip
env:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
install:
    - pip install "django<$DJANGO"
    - pip install .
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r tests/requirements/python2.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r tests/requirements/python3.txt; fi
script: fab test:coverage
